import type { LeaderboardModel } from './leaderboard';

export const LEADERBOARD_MODELS: LeaderboardModel[] = [
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    vibeScore: 98.2,
    speedTps: 71,
    costPer1k: 0.004,
    grade: 'A+',
    categories: ['Text', 'Coding', 'Image'],
    isOpenSource: false,
    usageRank: 1,
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    vibeScore: 96.1,
    speedTps: 65,
    costPer1k: 0.005,
    grade: 'A',
    categories: ['Text', 'Coding', 'Image'],
    isOpenSource: false,
    usageRank: 2,
  },
  {
    id: 'gemini-2-5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    vibeScore: 94.5,
    speedTps: 88,
    costPer1k: 0.001,
    grade: 'A',
    categories: ['Text', 'Speed', 'Image'],
    isOpenSource: false,
    usageRank: 3,
  },
  {
    id: 'claude-3-opus',
    name: 'Claude 3 Opus',
    provider: 'Anthropic',
    vibeScore: 93.4,
    speedTps: 28,
    costPer1k: 0.015,
    grade: 'A',
    categories: ['Text', 'Coding'],
    isOpenSource: false,
    usageRank: 6,
  },
  {
    id: 'gemini-2-5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    vibeScore: 92.6,
    speedTps: 54,
    costPer1k: 0.007,
    grade: 'A',
    categories: ['Text', 'Coding', 'Image'],
    isOpenSource: false,
    usageRank: 4,
  },
  {
    id: 'llama-3-3-70b',
    name: 'Llama 3.3 70B',
    provider: 'Meta',
    vibeScore: 91.0,
    speedTps: 57,
    costPer1k: 0.0009,
    grade: 'B+',
    categories: ['Text', 'Coding'],
    isOpenSource: true,
    usageRank: 7,
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'OpenAI',
    vibeScore: 89.7,
    speedTps: 42,
    costPer1k: 0.01,
    grade: 'B+',
    categories: ['Text', 'Coding'],
    isOpenSource: false,
    usageRank: 9,
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'DeepSeek',
    vibeScore: 88.5,
    speedTps: 63,
    costPer1k: 0.0006,
    grade: 'B+',
    categories: ['Text', 'Coding'],
    isOpenSource: true,
    usageRank: 8,
  },
  {
    id: 'mixtral-8x22b',
    name: 'Mixtral 8x22B',
    provider: 'Mistral',
    vibeScore: 87.3,
    speedTps: 49,
    costPer1k: 0.0008,
    grade: 'B',
    categories: ['Text', 'Coding'],
    isOpenSource: true,
    usageRank: 11,
  },
  {
    id: 'grok-4',
    name: 'Grok 4',
    provider: 'xAI',
    vibeScore: 86.2,
    speedTps: 78,
    costPer1k: 0.003,
    grade: 'B+',
    categories: ['Text', 'Speed'],
    isOpenSource: false,
    usageRank: 12,
  },
  {
    id: 'kimi-k2-5',
    name: 'Kimi K2.5',
    provider: 'Moonshot',
    vibeScore: 84.9,
    speedTps: 92,
    costPer1k: 0.002,
    grade: 'B',
    categories: ['Text', 'Speed'],
    isOpenSource: false,
    usageRank: 10,
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    vibeScore: 82.1,
    speedTps: 110,
    costPer1k: 0.0006,
    grade: 'B',
    categories: ['Text', 'Speed', 'Image'],
    isOpenSource: false,
    usageRank: 5,
  },
  {
    id: 'mistral-small-3',
    name: 'Mistral Small 3',
    provider: 'Mistral',
    vibeScore: 79.3,
    speedTps: 95,
    costPer1k: 0.0004,
    grade: 'B',
    categories: ['Text', 'Speed'],
    isOpenSource: true,
    usageRank: 14,
  },
  {
    id: 'llama-3-1-8b',
    name: 'Llama 3.1 8B',
    provider: 'Meta',
    vibeScore: 76.4,
    speedTps: 145,
    costPer1k: 0.0002,
    grade: 'C+',
    categories: ['Text', 'Speed'],
    isOpenSource: true,
    usageRank: 13,
  },
  {
    id: 'phi-3-5',
    name: 'Phi-3.5',
    provider: 'Microsoft',
    vibeScore: 73.8,
    speedTps: 130,
    costPer1k: 0.0003,
    grade: 'C+',
    categories: ['Text', 'Speed'],
    isOpenSource: true,
    usageRank: 15,
  },
];
